name: CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  pipeline:
    uses: msm-oc-projects/msm-projet-06-ops/.github/workflows/ci.yml@main

  release:
    needs: pipeline
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    uses: msm-oc-projects/msm-projet-06-ops/.github/workflows/release.yml@main
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
